# Generated by Django 5.2.7 on 2025-11-11 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ESGScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co2_impact', models.FloatField()),
                ('sustainability_rating', models.FloatField()),
            ],
        ),
    ]
